services:
  web:
    build: .
    working_dir: /app
    volumes:
      - ./myapp:/app
      - bundle:/usr/local/bundle
    ports:
      - "2300:2300"
      - "9293:9293"
    tty: true
    depends_on:
      - db
    command: bundle exec hanami server

  db:
    restart: always
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - 3306:3306

volumes:
  bundle:
  mysql_data:
